# Generated by Django 4.0.4 on 2022-05-31 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("walets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_amount",
                    models.DecimalField(
                        decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        editable=False,
                        max_digits=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "PAID"), ("failed", "FAILED")],
                        default="paid",
                        editable=False,
                        max_length=6,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to="walets.wallet",
                        to_field="name",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to="walets.wallet",
                        to_field="name",
                    ),
                ),
            ],
        ),
    ]
