# Generated by Django 4.0.4 on 2022-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="commission",
            field=models.DecimalField(
                decimal_places=2, default=0.0, editable=False, max_digits=100
            ),
        ),
    ]
