# Generated by Django 4.0.4 on 2022-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("failed", "Failed")],
                default="paid",
                editable=False,
                max_length=6,
            ),
        ),
    ]
