# Generated by Django 4.0.4 on 2022-06-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("rub", "RUB"), ("usd", "USD"), ("eur", "EUR")],
                default="rub",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="type",
            field=models.CharField(
                choices=[("visa", "Visa"), ("mastercard", "Mastercard")],
                default="visa",
                max_length=10,
            ),
        ),
    ]
