# Generated by Django 4.0.4 on 2022-05-31 07:05

from django.db import migrations, models

import walets.models


class Migration(migrations.Migration):

    dependencies = [
        ("walets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.SlugField(
                default=walets.models.Wallet.wallet_name_generator,
                editable=False,
                max_length=8,
                unique=True,
            ),
        ),
    ]
