# Generated by Django 4.0.4 on 2022-06-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("walets", "0002_alter_wallet_currency_alter_wallet_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                default="rub",
                max_length=3,
            ),
        ),
    ]
